basePath: /
host: localhost:8010
info:
  contact:
    email: adamcgladstone@gmail.com
    name: Web Service Gin API Support
    url: http://www.swagger.io/support
  description: This is  a Web Service Gin server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Web Service Gin Swagger API
  version: "1.0"
paths:
  /albums:
    get:
      consumes:
      - application/json
      description: get albums
      parameters:
      - description: name search by q
        format: email
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses: {}
      summary: List albums
      tags:
      - albums
  /albums/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Album ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Show an albums
      tags:
      - albums
schemes:
- http
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
